version: "3.7"

x-defaults:
  network: &network
    networks:
      - net

services:
  php:
    image: lamp
    ports:
      - 80:80
      - 443:443
    volumes:
      - workspace:/var/www
    configs:
      - source: apache-vhosts
        target: /etc/apache2/sites-available/000-default.conf
      - source: php-ini
        target: /usr/local/etc/php/conf.d/local.ini
    environment:
      - WORDPRESS_DB_NAME=webhypothesis
      - WORDPRESS_DB_USER=webhypothesis
      - WORDPRESS_DB_PASSWORD=hCFA2Pe}vakvqU}CEQ3T
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_CHARSET=utf8
    <<: *network

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_pwd
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
    volumes:
      - data:/var/lib/mysql
    secrets:
      - db_pwd
    <<: *network

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=sup3rs3cr3tp4ssw0rd
      - UPLOAD_LIMIT=20M
    <<: *network

networks:
  net:

secrets:
  db_pwd:
    file: ./mysql/root_password.txt

configs:
  apache-vhosts:
    file: ./apache/vhosts.conf
  php-ini:
    file: ./php/local.ini

volumes: 
  workspace:
     external: true 
  data:
     external: true
